version: 3

env:
  #ENV: dev
  #ENV: testing
  #ENV: staging
  ENV: production

dotenv: ['.env', '{{ .taskEnv }}']

includes:
  # General tasks from your distribution file
  dist:
    taskfile: Taskfile.dist.yaml
    internal: false # Ensures these tasks are visible in --list

  # Local, repo-specific tasks
  local:
    taskfile: Taskfile.local.yaml
    optional: true  # Prevents errors if the local file is missing
